Repository valentin-dlack/livechat-obs, pull requests merged in 2025-01, with the labels that each got.

#4 feat(messages): mp3 audio files support on livechat
  public/styles.css
  views/index.ejs
Labels: enhancement

#5 feat(command): add stop command
  src/commands/stop.js
  views/index.ejs
Labels: enhancement

#7 feat(unit-tests): added units tests & github actions
  .github/workflows/test.yaml
  jest.config.js
  package-lock.json
  package.json
  tests/services/commandHandler.test.js
  tests/services/stateManager.test.js
Labels: enhancement

#8 fix(view): fixed audio stopping after 10 seconds
  views/index.ejs
Labels: bug

#9 Release V1.0
  .env.example
  .github/workflows/test.yaml
  .husky/commit-msg
  .husky/pre-commit
  .husky/scripts/check-commit-msg.sh
  .husky/scripts/lint.sh
  .prettierrc
  .vscode/settings.json
  README.md
  bot.js
  eslint.config.mjs
  jest.config.js
  package-lock.json
  package.json
  public/styles.css
  src/commands/help.js
  src/commands/register.js
  src/commands/stell.js
  src/commands/stop.js
  src/commands/tell.js
  src/config/config.js
  src/index.js
  src/server/express.js
  src/services/commandHandler.js
  src/services/messageHandler.js
  src/services/stateManager.js
  src/services/websocket.js
  tests/services/commandHandler.test.js
  tests/services/stateManager.test.js
  views/index.ejs
Labels: documentation, enhancement
